{
  "name": "syntax-presence-api",
  "version": "1.0.0",
  "type": "commonjs",
  "scripts": {
    "dev": "tsx watch src/index.ts",
    "build": "tsc && cp src/index.js src/index.js",
    "start": "node src/index.js"
  },
  "dependencies": {
    "discord.js": "^14.16.3",
    "dotenv": "^16.4.5",
    "express": "^4.19.2"
  },
  "devDependencies": {
    "tsx": "^4.15.7",
    "typescript": "^5.5.4"
  }
}
