services:
  presence-api:
    build: .
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      USER_IDS: ${USER_IDS}
      PORT: "3000"
      PUBLIC_READ: "false"
      API_KEY: ${API_KEY}
      CACHE_SECONDS: "20"
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
